apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rytnow-me
resources:
  - ../../base
commonLabels:
  environment: production
images:
  - name: ghcr.io/rahulvramesh/rytnow-me
    newTag: latest
