apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trakx.fullname" . }}-secrets
  labels:
    {{- include "trakx.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_KEY: {{ .Values.app.key | quote }}
  DB_USERNAME: {{ .Values.postgresql.auth.username | quote }}
  DB_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  REDIS_PASSWORD: ""
  REVERB_APP_KEY: {{ .Values.reverb.appKey | quote }}
  REVERB_APP_SECRET: {{ .Values.reverb.appSecret | quote }}
  VITE_REVERB_APP_KEY: {{ .Values.reverb.appKey | quote }}
  VITE_REVERB_HOST: {{ .Values.reverb.host | quote }}
  VITE_REVERB_PORT: {{ .Values.reverb.port | quote }}
  VITE_REVERB_SCHEME: {{ .Values.reverb.scheme | quote }}
  {{- if .Values.liveblocks.publicKey }}
  VITE_LIVEBLOCKS_PUBLIC_KEY: {{ .Values.liveblocks.publicKey | quote }}
  {{- end }}
  {{- if .Values.liveblocks.secretKey }}
  LIVEBLOCKS_SECRET_KEY: {{ .Values.liveblocks.secretKey | quote }}
  {{- end }}
