apiVersion: v1
kind: Service
metadata:
  name: {{ include "trakx.fullname" . }}
  labels:
    {{- include "trakx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.reverbPort }}
      targetPort: reverb
      protocol: TCP
      name: reverb
  selector:
    {{- include "trakx.selectorLabels" . | nindent 4 }}
