apiVersion: v1
kind: ConfigMap
metadata:
  name: trakx-config
  namespace: trakx
data:
  APP_NAME: "Trakx"
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "https://rytnow-me.trakx.app"
  APP_LOCALE: "en"
  APP_FALLBACK_LOCALE: "en"
  APP_FAKER_LOCALE: "en_US"
  APP_MAINTENANCE_DRIVER: "file"
  BCRYPT_ROUNDS: "12"
  LOG_CHANNEL: "stack"
  LOG_STACK: "single"
  LOG_LEVEL: "error"
  DB_CONNECTION: "pgsql"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_DATABASE: "trakx"
  SESSION_DRIVER: "redis"
  SESSION_LIFETIME: "120"
  SESSION_ENCRYPT: "false"
  SESSION_PATH: "/"
  BROADCAST_CONNECTION: "reverb"
  FILESYSTEM_DISK: "local"
  QUEUE_CONNECTION: "redis"
  CACHE_STORE: "redis"
  REDIS_CLIENT: "phpredis"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REVERB_APP_ID: "trakx-prod"
  REVERB_HOST: "rytnow-me.trakx.app"
  REVERB_PORT: "443"
  REVERB_SCHEME: "https"
  MAIL_MAILER: "log"
