apiVersion: v2
name: trakx
description: Trakx - Project Management Application
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: "16.4.3"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "20.6.2"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
