apiVersion: v1
kind: ConfigMap
metadata:
  name: trakx-config
data:
  APP_NAME: "Trakx"
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "https://rytnow.me"
  ASSET_URL: "https://rytnow.me"
  APP_LOCALE: "en"
  APP_FALLBACK_LOCALE: "en"
  APP_MAINTENANCE_DRIVER: "file"
  BCRYPT_ROUNDS: "12"
  LOG_CHANNEL: "stack"
  LOG_STACK: "single"
  LOG_LEVEL: "error"
  DB_CONNECTION: "pgsql"
  DB_HOST: "postgresql"
  DB_PORT: "5432"
  DB_DATABASE: "trakx"
  DB_USERNAME: "trakx"
  SESSION_DRIVER: "redis"
  SESSION_LIFETIME: "120"
  SESSION_ENCRYPT: "false"
  SESSION_PATH: "/"
  BROADCAST_CONNECTION: "reverb"
  FILESYSTEM_DISK: "local"
  QUEUE_CONNECTION: "redis"
  CACHE_STORE: "redis"
  REDIS_CLIENT: "phpredis"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REVERB_APP_ID: "trakx-prod"
  REVERB_HOST: "rytnow.me"
  REVERB_PORT: "443"
  REVERB_SCHEME: "https"
  REVERB_SERVER_HOST: "0.0.0.0"
  REVERB_SERVER_PORT: "8080"
  MAIL_MAILER: "resend"
  MAIL_FROM_ADDRESS: "noreply@rytnow.me"
  MAIL_FROM_NAME: "Trakx"
