apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trakx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - rytnow.me
      secretName: rytnow-me-tls
  rules:
    - host: rytnow.me
      http:
        paths:
          - path: /app
            pathType: Prefix
            backend:
              service:
                name: trakx
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: trakx
                port:
                  number: 80
