apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rytnow-me
resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - postgresql.yaml
  - redis.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
commonLabels:
  app.kubernetes.io/name: trakx
